### ISSUE TITLE
Building from Tor Project's sources

### ISSUE THREAD

**Issue by ericlagergren** [jayluxferro/snowflake#1]
As far as I can tell, `snowflake.js` is generated with

```
cat broker.js config.js proxypair.js snowflake.js ui.js util.js websocket.js shims.js init-webext.js
```

It would be nice if you added a script to generate `snowflake.js` so it could be compared against the Tor Project's sources.

**Comment by jayluxferro** [comment]
Thanks @ericlagergren. I will do that.

**Comment by ericlagergren** [comment]
And thank you for this extension!

**Comment by jayluxferro** [comment]
Hello @ericlagergren , I've implemented what you suggested. Please try it out and let me know if it's okay. Thank you.

**Comment by ericlagergren** [comment]
@jayluxferro wonderful, thank you!
